# Generated by Django 4.2.17 on 2025-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='運動名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('calories_burned_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='每小時燃燒卡路里')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
    ]
