# Generated by Django 4.2.17 on 2025-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='每小時燃燒卡路里'),
        ),
    ]
