# Generated by Django 4.2.17 on 2025-01-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exercise_name_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(verbose_name='次數')),
                ('sets', models.IntegerField(verbose_name='組數')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='重量(kg)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.movement')),
            ],
        ),
    ]
